### ISSUE TITLE
[bug] accidentally converts a multiline attribute into multiple attributes

### ISSUE THREAD

**Issue by trusktr** [ryansolid/html-parse-string#3]
Continued from https://github.com/ryansolid/dom-expressions/issues/143

input:

```html
     <div
            multiline="
              foo
              bar
            "
          ></div>
```

output:

```js
     [
      {
        type: 'tag',
        name: 'div',
        voidElement: false,
        attrs: { foo: '', bar: '' },
        children: []
      }
    ]
```

**Comment by trusktr** [comment]
What if we switch to this: https://npmjs.com/html-dom-parser

It falls back to the native DOM parser on the client, and it gets the parsing correct.

Was the regex faster than DOM APIs on the client?

I'm having a hard time getting the regex to work well for all the attribute cases (still trying...).

**Comment by trusktr** [comment]
Here's the new test input I'm using (all are valid HTML attributes, but not all valid attributes possible are included yet):

```html
`
<div
	  blah lorem
	  foo-bar
            multi-line="
   	         foo
              bar
            "
				bar=" asdf"
				baz=  zxcv 
				foo=asdf
				aa=df-bar=()
				a-b=df-b"ar=()
				ac=df"-bar=()
				ad=df-bar=()
          ></div>
			 
`
```

Here's that sample [on `runkit` using `html-dom-parser`](https://runkit.com/embed/2iqw0hnh7931).

**Comment by trusktr** [comment]
For reference, here are the results of the current regex here in `html-parse-string`:

https://regexr.com/6p8dc

Here's one that catches more results, but still not there yet:

https://regexr.com/6p82g

**Comment by ryansolid** [comment]
Yeah.. hmm this is super old. We could swap it out. I used this library because I was familiar with it, and it was something I had done back in the knockout days. I had forked a different library and added some functionality (because the original didn't properly handle web components). I'm almost positive there are better solutions.

**Comment by trusktr** [comment]
Hmm. I can't find a single regex that catches them all yet, but I did find a two-step approach using two regexes. First we extract all the attributes with values like so:

https://regexr.com/6p82j

Then we delete those matches from the string, and we can finally extract the remaining boolean attributes:

https://regexr.com/6p8on

**Comment by trusktr** [comment]
Ah wait, I got it!

https://regexr.com/6p8p0

PR coming up...

**Comment by trusktr** [comment]
PR: https://github.com/ryansolid/html-parse-string/pull/4

**Comment by ivanjeremic** [comment]
I know this is a resolved issue, but I would like to know why this library is needed when there is the DomParser API in the Browser? Why not use DomParser API for dom-expression instead of this?
